# Generated by Django 2.2.11 on 2020-09-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Truth',
            new_name='Truth1',
        ),
    ]
