# Generated by Django 2.2.11 on 2020-09-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200920_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truth',
            name='Truth',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='truth',
            name='reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
