# Generated by Django 2.1.4 on 2020-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20200920_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='truth',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
