# Generated by Django 3.1.2 on 2020-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20201005_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='truth',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
